export const SET_IS_MOBILE = 'SET_IS_MOBILE';
export const SET_CONFIRM_MESSAGE = 'SET_CONFIRM_MESSAGE';

export const SET_USER = 'SET_USER';
export const SET_ANSWER_HISTORY = 'SET_ANSWER_HISTORY';
export const INIT_CURRENT_USER_SUCCESS = 'INIT_CURRENT_USER_SUCCESS';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const UPDATING_CURRENT_USER_SUCCESS = 'UPDATING_CURRENT_USER_SUCCESS';
export const UPDATING_DISPLAYED_ANSWER_HISTORY_SUCCESS = 'UPDATING_DISPLAYED_ANSWER_HISTORY_SUCCESS';

export const UPDATING_NEW_CONTENTS_SUCCESS = 'UPDATING_NEW_CONTENTS_SUCCESS';
export const SET_CONTENT = 'SET_CONTENT';
export const CREATING_CONTENT_SUCCESS = 'CREATING_CONTENT_SUCCESS';
export const UPDATING_DISPLAYED_CONTENT_SUCCESS = 'UPDATING_DISPLAYED_CONTENT_SUCCESS';

export const CREATING_ANSWER_HISTORY_SUCCESS = 'CREATING_ANSWER_HISTORY_SUCCESS';
export const UPDATING_ANSWER_HISTORY_CONTENT_REQUEST = 'UPDATING_ANSWER_HISTORY_CONTENT_REQUEST';
export const FINISH_ANSWER_HISTORY_SUCCESS = 'FINISH_ANSWER_HISTORY_SUCCESS';

export const CACHE_CONTENT_NEW_VALUES = 'CACHE_CONTENT_NEW_VALUES';
export const CACHE_SEARCH_VALUES = 'CACHE_SEARCH_VALUES';

export const SET_NEWS = 'SET_NEWS';
export const FETCHING_NEWS_SUCCESS = 'FETCHING_NEWS_SUCCESS';
